project_1/wiki/encyclopedia/urls.py
from django.urls import path

from . import views


app_name = "wiki"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.title, name="title"),
    path("create_new_entry/", views.new_entry, name="new_entry"),
    path("wiki/<str:title>/edit", views.edit, name="edit"),
    path("random_page/", views.random_page, name="random_page"), 
    ]

project_1/wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    # changed from / to wiki/
    path('', include("encyclopedia.urls"))
]

project_1/wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

project_1/wiki/encyclopedia/views.py
from logging import PlaceHolder
from django.shortcuts import render
from . import util
import markdown2
from django import forms
import re
import random


class Search(forms.Form):
    title = forms.CharField(label="", widget=forms.TextInput(attrs={'placeholder': 'Search Encyclopedia'}))

class EntryTitle(forms.Form):
    entry_title = forms.CharField(label="Entry Titel", widget=forms.TextInput(attrs={'placeholder': 'Write Title'}))
    entry_content = forms.CharField(label="", widget=forms.Textarea(attrs={'placeholder': 'Write Content'}))

class Edit(forms.Form):
    textarea = forms.CharField(widget=forms.Textarea(), label='')


def random_page(request):
    name_of_page = random.choice(util.list_entries())
    content_of_title = util.get_entry(name_of_page)
    converted_content_of_title = markdown2.markdown(content_of_title)
    return render(request, "encyclopedia/title.html", {
            "title_up": name_of_page,
            "converted_content_of_title": converted_content_of_title,
            "form": Search()
        })

def edit(request, title):
    if request.method == 'POST':
        form = Edit(request.POST) 
        if form.is_valid():
            textarea = form.cleaned_data["textarea"]
            util.save_entry(title,textarea)
            content = util.get_entry(title)
            content_converted = markdown2.markdown(content)
            return render(request, "encyclopedia/title.html", {
                'form': Search(),
                'converted_content_of_title': content_converted,
                'title_up': title
            })

    else: #GET
        content = util.get_entry(title)
        return render(request, "encyclopedia/edit.html", {
            'content_to_edit': Edit(initial={'textarea': content}),
            'title_up': title,
            'form': Search(),
        })


def new_entry(request):
    if request.method == "POST":
        entry_title_post = EntryTitle(request.POST)
        #entry_content_post = EntryContent(request.POST)
        if entry_title_post.is_valid():
            title_saved = entry_title_post.cleaned_data["entry_title"]
            content_saved = entry_title_post.cleaned_data["entry_content"]
            all_entries = util.list_entries()
            for search in all_entries:
                if title_saved.lower() == search.lower():
                    return render(request, "encyclopedia/new_entry.html", {
                    "entry_title_get": EntryTitle(),
                    "error_message": "This Entry already exist",
                    "form": Search()
                    })
            util.save_entry(title_saved, content_saved)
            #return title(request, title_saved) # not sure if this is allowed
            #  Why title is not seen in URL????
            content_of_title = util.get_entry(title_saved)
            converted_content_of_title = markdown2.markdown(content_of_title)
            return render(request, "encyclopedia/title.html", {
                    "title_up": title_saved,
                    "converted_content_of_title": converted_content_of_title,
                    "form": Search()
                })
            #return HttpResponseRedirect('/wiki/<str:title_saved>')
        else:
            return render(request, "encyclopedia/new_entry.html", {
                "entry_title_get": EntryTitle(),
                #"entry_content_get": EntryContent(),
                "form": Search()
            })  
    else: #GET
        return render(request, "encyclopedia/new_entry.html", {
                    "entry_title_get": EntryTitle(),
                    #"entry_content_get": EntryContent(),
                    "form": Search()
                })

def index(request):
    if request.method == "POST":
        form = Search(request.POST)
        if form.is_valid():
            title_searched = form.cleaned_data["title"]
            all_entries = util.list_entries()
            substring_list = []
            for search in all_entries:
                if search.lower() == title_searched.lower():
                    #return title(request, search) # not sure if this is allowed
                    #  Why title is not seen in URL????
                    content_of_title = util.get_entry(search)
                    converted_content_of_title = markdown2.markdown(content_of_title)
                    return render(request, "encyclopedia/title.html", {
                            "title_up": search,
                            "converted_content_of_title": converted_content_of_title,
                            "form": Search()
                        })
                elif re.findall(title_searched.lower(), search.lower()):
                    substring_list.append(search)
            if len(substring_list) >= 1:
                return render(request, "encyclopedia/search.html", {
                        "entries": substring_list,
                        # How to avoid redundancy with the NetTaskForm() which appears on various places??
                        "form": Search()
                        })
            else:
                return render(request, "encyclopedia/index.html", {
                "form": Search(),
                "no_results": "No results found."
                })
                   
        else:
            return render(request, "encyclopedia/index.html", {
                        "entries": util.list_entries(),
                        "form": Search()
                    })

    else: # GET
        return render(request, "encyclopedia/index.html", {
            "entries": util.list_entries(),
            "form": Search(),
        })
        

def title(request, title):
    if util.get_entry(title) is None:
            error_message = "Your requested page was not found. Try another."
            error_code = "404 Not Found"
            return render(request, "encyclopedia/error.html", {
                "error_message": error_message,
                "title_up": error_code,
                "form": Search()
            })
    else:
        content_of_title = util.get_entry(title)
        converted_content_of_title = markdown2.markdown(content_of_title)
        return render(request, "encyclopedia/title.html", {
                "title_up": title,
                "converted_content_of_title": converted_content_of_title,
                "form": Search()
            })

project_1/wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}


{% block title %}
    {{ title_up }}
{% endblock %}


{% block body %}

<form method="post" >
    {% csrf_token %}
    <h2>Edit</h2>
        {{ content_to_edit }}
    <br>
    <input type="submit" value="Save"/>
</form>

{% endblock %}

project_1/wiki/encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title_up }}
{% endblock %}

{% block body %}

{{ error_message }}

{% endblock %}

project_1/wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Encyclopedia</h1>

    <ul>
        {% for entry in entries %}
            <li><a href=/wiki/{{entry}}>{{ entry }}</a></li>
        {% endfor %}
    </ul>
    

    {{ no_results }}


{% endblock %}

project_1/wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'wiki:index' %}" method="post">
                    {% csrf_token %}
                    {{ form }}
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:new_entry' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'wiki:random_page' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

project_1/wiki/encyclopedia/templates/encyclopedia/new_entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create New Page
{% endblock %}

{% block body %}

<div id="searching">

    <div>
        <h1>Create New Entry</h1>
     </div>

    <p style="color:red;">{{ error_message }}</p>

    <div>
        <!--<textarea value="entry_id" name="entry_title" placeholder="Write Title"></textarea>-->
        <!--<textarea value="entry_id" name="entry_content" placeholder="Write Markdown Content"></textarea>-->
        <form id=entry_id action="{% url 'wiki:new_entry' %}" method="post">
            {% csrf_token %}

            {{ entry_title_get }}
    
            <input type="submit" value="save">
        </form>
    </div>

</div>



{% endblock %}

project_1/wiki/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}


{% block title %}
    Searched Pages
{% endblock %}


{% block body %}

<h1>Encyclopedia</h1>

<ul>
    {% for entry in entries %}
        <li><a href=/wiki/{{entry}}>{{ entry }}</a></li>
    {% endfor %}
</ul>


{% endblock %}

project_1/wiki/encyclopedia/templates/encyclopedia/title.html
{% extends "encyclopedia/layout.html" %}


{% block title %}
    {{ title_up }}
{% endblock %}


{% block body %}

{{ converted_content_of_title |safe }}

<a href=/wiki/{{title_up}}/edit>Edit Page</a>

{% endblock %}